services:
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      # Asegúrate de que la URL de la base de datos esté configurada para producción
      DATABASE_URL: "ecto://postgres:postgres@db/preneur_challenge_prod"
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: preneur_challenge_prod
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
